spring:
  application:
    name: thread
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

file:
  path: /Users/11411360/Desktop/log/thread/db.json